### ISSUE TITLE
localStorage Error

### ISSUE THREAD

**Issue by Freetoplay951** [vuejs/devtools#979]
[request error] [unhandled] [GET] https://...
TypeError: localStorage.getItem is not a function
at getTimelineLayersStateFromStorage (/app/server/node_modules/@vue/devtools-kit/dist/index.cjs:2364:30)
... 8 lines matching cause stack trace ...
at Module.require (node:internal/modules/cjs/loader:1502:12) {
cause: TypeError: localStorage.getItem is not a function
at getTimelineLayersStateFromStorage (/app/server/node_modules/@vue/devtools-kit/dist/index.cjs:2364:30)
at initStateFactory (/app/server/node_modules/@vue/devtools-kit/dist/index.cjs:2657:26)
at Object. (/app/server/node_modules/@vue/devtools-kit/dist/index.cjs:2661:92)
at Module._compile (node:internal/modules/cjs/loader:1759:14)
at Object..js (node:internal/modules/cjs/loader:1892:10)
at Module.load (node:internal/modules/cjs/loader:1479:32)
at Module._load (node:internal/modules/cjs/loader:1298:12)
at TracingChannel.traceSync (node:diagnostics_channel:328:14)
at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
at Module.require (node:internal/modules/cjs/loader:1502:12),
statusCode: 500,
fatal: false,
unhandled: true,
statusMessage: undefined,
data: undefined
}

**Comment by alfUMi** [comment]
I have the same problem, I have already tried different methods, but nothing helped.

**Comment by webfansplz** [comment]
Fixed in v8.0.3

**Comment by alfUMi** [comment]
@webfansplz I use Nuxt Devtools and this package comes with Nuxt itself. How do I update the package in this case?

**Comment by webfansplz** [comment]
> [@webfansplz](https://github.com/webfansplz) I use Nuxt Devtools and this package comes with Nuxt itself. How do I update the package in this case?

Try to use `pnpm.overrides` to bump the deps in package.json:

```json
{
  "pnpm": {
    "overrides": {
       '@vue/devtools-applet': ^8.0.3,
       '@vue/devtools-core': ^8.0.3,
       '@vue/devtools-kit': ^8.0.3
    }
  }
}
```

**Comment by alfUMi** [comment]
I use npm😅

UPD: overrides with a 8.0.3 version helped.

**Comment by darel919** [comment]
I have this exact issue with my Nuxt 4 project. But using just this fix still doesn't fix it 

> > [@webfansplz](https://github.com/webfansplz) I use Nuxt Devtools and this package comes with Nuxt itself. How do I update the package in this case?
> 
> Try to use `pnpm.overrides` to bump the deps in package.json:
> 
> {
>   "pnpm": {
>     "overrides": {
>        '@vue/devtools-applet': ^8.0.3,
>        '@vue/devtools-core': ^8.0.3,
>        '@vue/devtools-kit': ^8.0.3
>     }
>   }
> }

However, It turns out when i regress my vue-router from 4.6.3 (latest as of Oct 25, 2025) to 4.5.1 (version before i upgraded) it works just fine. Hope this can helps someone!

**Comment by SandFoxed** [comment]
> Try to use pnpm.overrides to bump the deps in package.json:

Apparently npm has a similar function too, so you don't have to switch to pnpm just for this.
```json
  "overrides": {
    "@vue/devtools-kit": ">=8.0.3"
  }
```

**Comment by Dmseper** [comment]
this is a problem in NodeJS version 25, reverted to version 24.10, and then the problem was fixed.

**Comment by Ne0-Hack** [comment]
Rolling back to version 8.0.1 resolves the issue.

**Comment by diveshflame** [comment]
> > Try to use pnpm.overrides to bump the deps in package.json:
> 
> Apparently npm has a similar function too, so you don't have to switch to pnpm just for this.
> 
>   "overrides": {
>     "@vue/devtools-kit": ">=8.0.3"
>   }

This worked for me as well with 8.0.1

**Comment by Intevel** [comment]
Also solved when upgrading Nuxt to 4.2.1
